#include <ESP8266WiFi.h>
#include <HID-Project.h>

// WiFi Credentials
const char* ssid = "Your_SSID";
const char* password = "Your_Password";

// Flag to trigger keystroke injection
bool injectFlag = false;

// Keystroke injection payload
String attackPayload = "Hello from WHID Cactus ESP-12F!";

void setup() {
  // Initialize serial for debugging
  Serial.begin(115200);
  
  // Start WiFi connection
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print(".");
    delay(500);
  }
  Serial.println("\nWiFi connected!");

  // Start HID emulation
  Keyboard.begin();
}

void loop() {
  // Example: Set injectFlag to true after 5 seconds
  delay(5000);
  injectFlag = true;

  // Check for payload trigger
  if (injectFlag) {
    injectFlag = false;  // Reset the flag after the attack starts
    performAttack();
  }
}

void performAttack() {
  // Inject keystrokes
  Serial.println("Take My Load Baby!...");
  Keyboard.print(attackPayload);
  
  // End attack
  Keyboard.releaseAll();
}
